version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgsql:/var/lib/postgresql/data